### ISSUE TITLE
Token Action Hud won't open for players or NPCs - Console error: TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by Count-Funkula** [Larkinabout/fvtt-token-action-hud-pf2e#131]
When I select any character or NPC the HUD won't open and the console shows an error:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at #w (token-action-hud-pf2e.min.js:1:31256)
    at async Promise.all (index 12)
    at async #a (token-action-hud-pf2e.min.js:1:17483)
    at async ActionHandler.buildSystemActions (token-action-hud-pf2e.min.js:1:17005)
    at async #h (action-handler.js:208:72)
    at async Promise.all (index 0)
    at async ActionHandler.buildHud (action-handler.js:98:31)
    at async #It (token-action-hud.js:1157:14)
    at async TokenActionHud.update (token-action-hud.js:1093:20)

I've turned off all modules other than the ones required to run this one.

**Comment by Silvertower** [comment]
What is your version of Foundry and what is your version of PF2e system?

**Comment by Silvertower** [comment]
The code in question is sound. So, there is almost certainly a versioning issue with PF2e system.

To use Token Action HUD PF2e, the following is required:
Foundry VTT version 11.315 or later
PF2e system version 5.12.7 or later
Token Action HUD Core version 1.5.0 or later
socketlib version 1.0.13 or later

**Comment by Count-Funkula** [comment]
Sorry, you were right. I manually updated Foundry and PF2e system version - the update button for PF2e kept it at 5.3.2

Thanks so much for your help
